version: 2.1

executors:
  default:
    docker:
      - image: kahiro/node-nightmare
        environment:
          DISPLAY: ":99"
          GOOGLE_APPLICATION_CREDENTIALS: "/root/gcloud-service-key.json"
    environment:
      # CODECOV_TOKEN: xxx // setup via circleci
    working_directory: ~/reg-suit

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/reg-suit
          paths:
            - .

  build_storybook:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/reg-suit
      # storybookをビルドする
      - run:
          name: Generate Storybook
          command: |
            yarn build:storybook
      # Artifactsにアップロードする
      - store_artifacts:
          path: ./storybook-static
          destination: ~/storybook

  lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/reg-suit
      - run:
          name: Lint
          command: yarn run lint

  unit_test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/reg-suit
      - run:
          name: Test
          command: yarn run test:unit

  visual_regression_test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/reg-suit
      - run:
          name: setup GCP
          command: echo $GCLOUD_SERVICE_KEY | base64 -d > /root/gcloud-service-key.json
      - run:
          name: Screenshot
          command: yarn run screenshot
      - run:
          name: Regression
          command: yarn run regression

workflows:
  version: 2
  per_commit:
    jobs:
      - build:
          name: build
          filters:
            branches:
              only: /.*/
      - lint:
          name: lint
          requires:
            - build
          filters:
            branches:
              only: /.*/
      - unit_test:
          name: unit_test
          requires:
            - build
          filters:
            branches:
              only: /.*/
      - build_storybook:
          name: build_storybook
          requires:
            - build
          filters:
            branches:
              only: /.*/
      - visual_regression_test:
          name: visual_regression_test
          requires:
            - build
          filters:
            branches:
              only: /.*/
